"""Stable application-facing imports for the search kernel.

``searchkernel.api`` is the integration boundary for applications that own
source discovery and lifecycle orchestration. It groups the shared domain
values, ports, indexing contracts, persistence helpers, and search
configuration needed to compose those applications.

Application managers, watchers, source adapters, and private implementation
helpers remain outside this facade. Concrete local indexing adapters are
exposed only where they are reusable parts of the indexing seam; optional
backend providers remain in their adapter modules.
"""

from typing import TYPE_CHECKING, Any

from searchkernel.adapters.embedding.ollama import OllamaEmbeddingProvider
from searchkernel.compression import truncate_delta
from searchkernel.domain import (
    ActiveModelMetadata,
    BackupMetadata,
    ChangeSignal,
    Chunk,
    ChunkResult,
    CompressionStats,
    Cursor,
    GraphEdge,
    GraphNeighbor,
    MigrationPhase,
    MigrationState,
    ModelDimensionMismatchError,
    ModelNamespace,
    Record,
    RecordHit,
    RecordIdentity,
    RecordStatus,
    RollbackMetadata,
    SearchFilters,
    SearchResultProvenance,
    SearchStrategyStats,
    StrategyContribution,
    Tier,
    ValidationResult,
    Vector,
    canonical_storage_key,
)
from searchkernel.indexing.bootstrap_checkpoint import (
    BOOTSTRAP_CHECKPOINT_FILE_NAME,
    CURRENT_BOOTSTRAP_CHECKPOINT_SCHEMA_VERSION,
    BootstrapCheckpoint,
    BootstrapFileStamp,
    build_file_stamps,
    checkpoint_path,
    compute_bootstrap_generation,
    get_bootstrap_availability,
    get_semantic_completion_status,
    has_incomplete_bootstrap_checkpoint,
    load_bootstrap_checkpoint,
    mark_bootstrap_file_completed,
    mark_bootstrap_files_completed,
    mark_semantic_work_completed,
    prepare_bootstrap_checkpoint,
    publish_bootstrap_availability,
    save_bootstrap_checkpoint,
)
from searchkernel.indexing.bootstrap_snapshot import (
    BootstrapReadinessSnapshot,
    PublicIndexStateSnapshot,
    compute_bootstrap_completed_paths,
    derive_bootstrap_readiness_snapshot,
    derive_loaded_index_state_snapshot,
)
from searchkernel.indexing.checkpoints import JsonCheckpointStore, MemoryCheckpointStore
from searchkernel.indexing.coordinator import (
    CoordinatorProgress,
    CoordinatorReceipt,
    ResumableSemanticCoordinator,
)
from searchkernel.indexing.discovery import (
    PARSER_SUFFIXES,
    discover_files,
    discover_files_multi_root,
    get_parser_suffixes,
    is_excluded_dir,
    walk_dirs_with_files,
    walk_included_dirs,
)
from searchkernel.indexing.embedding_cache import (
    EmbeddingCacheMetrics,
    SQLiteEmbeddingCache,
)
from searchkernel.indexing.manifest import (
    CURRENT_MANIFEST_SPEC_VERSION,
    IndexManifest,
    load_manifest,
    save_manifest,
    should_rebuild,
)
from searchkernel.indexing.reconciler import (
    build_indexed_files_map,
    find_excluded_indexed_files,
    reconcile_indices,
)
from searchkernel.indexing.runtime_readiness import (
    IndexAvailability,
    IndexStatus,
    ReadinessStage,
    SearchAvailability,
    SemanticAvailability,
    can_refresh_loaded_indices,
    can_serve_queries,
    is_fully_ready,
    semantic_tier_from_progress,
)
from searchkernel.indexing.semantic import (
    EmbeddingCache,
    EmbeddingEncoder,
    EncoderFingerprint,
    LlamaIndexEmbeddingCacheAdapter,
    SemanticInput,
    SemanticTier,
    build_embedding_text,
    embedding_identity,
    semantic_input_for_chunk,
    semantic_input_for_record,
)
from searchkernel.indexing.submission import (
    TaskBatchSubmissionResult,
    TaskSubmissionResult,
)
from searchkernel.ingestion.records import SemanticRecordIngestor
from searchkernel.kernel import SearchKernel
from searchkernel.local import LocalRecordKernel, build_local_record_kernel
from searchkernel.ports import (
    FEDERATION_CONTRACT_VERSION,
    MAX_QUERY_LENGTH,
    MAX_RERANK_TEXT_LENGTH,
    MAX_SNIPPET_LENGTH,
    MAX_TOP_K,
    ActiveModelStore,
    AsyncEmbeddingProvider,
    AsyncGraphStore,
    AsyncKeywordStore,
    AsyncRecordHydrator,
    AsyncRecordIngestor,
    AsyncVectorStore,
    BatchContentSource,
    BatchGraphStore,
    BatchRecordHydrator,
    CacheStore,
    CallerAuthorizationContext,
    CandidateFilterSupport,
    CheckpointStore,
    ChunkTuningConfig,
    ContentSource,
    EmbeddingBatchProvider,
    EmbeddingProvider,
    EmbeddingSink,
    FederationSourceCapabilities,
    GraphStore,
    IndexManagerPort,
    IngestionError,
    IngestionFailureMode,
    IngestionReceipt,
    KeywordStore,
    LLMProvider,
    ModelBackupStore,
    ModelLifecycleStore,
    ModelNamespaceStore,
    ModelValidationStore,
    OrchestratorConfig,
    RecordIngestionResult,
    RecordIngestionStatus,
    RecordIngestor,
    RecordSearchFailure,
    RecordSearchOutcome,
    RecordSearchResult,
    Reranker,
    RetrievalFieldExtractor,
    RetrievalFields,
    SearchAPI,
    SearchHit,
    SearchHitProvenance,
    SearchRequest,
    SearchResponse,
    SearchSource,
    SourceBatch,
    SourceCapabilities,
    SourceIdentity,
    VectorStore,
    extract_retrieval_fields,
)
from searchkernel.runtime.reindex import (
    ReindexError,
    ReindexProgress,
    ReindexRoutine,
)
from searchkernel.search import (
    QueryPlan,
    QueryRouter,
    QueryRouterConfig,
    RecordSearchPipeline,
    SearchOrchestrator,
    route_query,
)
from searchkernel.search.edge_types import infer_edge_type
from searchkernel.search.path_utils import (
    compute_doc_id,
    compute_doc_id_multi_root,
    extract_doc_id_from_chunk_id,
    matches_any_excluded,
    normalize_path,
    resolve_doc_path,
    resolve_doc_path_multi_root,
)
from searchkernel.search.record_pipeline import (
    QueryEmbeddingProvider,
    RecordHydrator,
    RecordSearchCandidate,
    RecordSearchConfig,
    RecordSearchError,
    RecordSearchPolicy,
)
from searchkernel.search.utils import classify_query_type, truncate_content
from searchkernel.storage import DatabaseManager, SQLiteTuning
from searchkernel.utils import (
    cosine_similarity,
    cosine_similarity_lists,
    should_include_file,
)
from searchkernel.utils.atomic_io import atomic_write_json

if TYPE_CHECKING:
    from searchkernel.chunking import (
        ChunkingStrategy,
        HeaderBasedChunker,
        get_chunker,
    )
    from searchkernel.embeddings import (
        TEST_FAKE_EMBEDDING_MODEL_NAME,
        TEST_FAKE_EMBEDDINGS_ENV_VAR,
        should_use_test_fake_embeddings,
    )


def __getattr__(name: str) -> Any:
    if name in {
        "TEST_FAKE_EMBEDDING_MODEL_NAME",
        "TEST_FAKE_EMBEDDINGS_ENV_VAR",
        "should_use_test_fake_embeddings",
    }:
        from searchkernel import embeddings

        return getattr(embeddings, name)
    if name == "ChunkingStrategy":
        from searchkernel.chunking import ChunkingStrategy

        return ChunkingStrategy
    if name == "HeaderBasedChunker":
        from searchkernel.chunking import HeaderBasedChunker

        return HeaderBasedChunker
    if name == "get_chunker":
        from searchkernel.chunking import get_chunker

        return get_chunker
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "BOOTSTRAP_CHECKPOINT_FILE_NAME",
    "CURRENT_BOOTSTRAP_CHECKPOINT_SCHEMA_VERSION",
    "CURRENT_MANIFEST_SPEC_VERSION",
    "FEDERATION_CONTRACT_VERSION",
    "MAX_QUERY_LENGTH",
    "MAX_RERANK_TEXT_LENGTH",
    "MAX_SNIPPET_LENGTH",
    "MAX_TOP_K",
    "PARSER_SUFFIXES",
    "TEST_FAKE_EMBEDDINGS_ENV_VAR",
    "TEST_FAKE_EMBEDDING_MODEL_NAME",
    "ActiveModelMetadata",
    "ActiveModelStore",
    "AsyncEmbeddingProvider",
    "AsyncGraphStore",
    "AsyncKeywordStore",
    "AsyncRecordHydrator",
    "AsyncRecordIngestor",
    "AsyncVectorStore",
    "BackupMetadata",
    "BatchContentSource",
    "BatchGraphStore",
    "BatchRecordHydrator",
    "BootstrapCheckpoint",
    "BootstrapFileStamp",
    "BootstrapReadinessSnapshot",
    "CacheStore",
    "CallerAuthorizationContext",
    "CandidateFilterSupport",
    "ChangeSignal",
    "CheckpointStore",
    "Chunk",
    "ChunkResult",
    "ChunkTuningConfig",
    "ChunkingStrategy",
    "CompressionStats",
    "ContentSource",
    "CoordinatorProgress",
    "CoordinatorReceipt",
    "Cursor",
    "DatabaseManager",
    "EmbeddingBatchProvider",
    "EmbeddingCache",
    "EmbeddingCacheMetrics",
    "EmbeddingEncoder",
    "EmbeddingProvider",
    "EmbeddingSink",
    "EncoderFingerprint",
    "FederationSourceCapabilities",
    "GraphEdge",
    "GraphNeighbor",
    "GraphStore",
    "HeaderBasedChunker",
    "IndexAvailability",
    "IndexManagerPort",
    "IndexManifest",
    "IndexStatus",
    "IngestionError",
    "IngestionFailureMode",
    "IngestionReceipt",
    "JsonCheckpointStore",
    "KeywordStore",
    "LLMProvider",
    "LlamaIndexEmbeddingCacheAdapter",
    "LocalRecordKernel",
    "MemoryCheckpointStore",
    "MigrationPhase",
    "MigrationState",
    "ModelBackupStore",
    "ModelDimensionMismatchError",
    "ModelLifecycleStore",
    "ModelNamespace",
    "ModelNamespaceStore",
    "ModelValidationStore",
    "OllamaEmbeddingProvider",
    "OrchestratorConfig",
    "PublicIndexStateSnapshot",
    "QueryEmbeddingProvider",
    "QueryPlan",
    "QueryRouter",
    "QueryRouterConfig",
    "ReadinessStage",
    "Record",
    "RecordHit",
    "RecordHydrator",
    "RecordIdentity",
    "RecordIngestionResult",
    "RecordIngestionStatus",
    "RecordIngestor",
    "RecordSearchCandidate",
    "RecordSearchConfig",
    "RecordSearchError",
    "RecordSearchFailure",
    "RecordSearchOutcome",
    "RecordSearchPipeline",
    "RecordSearchPolicy",
    "RecordSearchResult",
    "RecordStatus",
    "ReindexError",
    "ReindexProgress",
    "ReindexRoutine",
    "Reranker",
    "ResumableSemanticCoordinator",
    "RetrievalFieldExtractor",
    "RetrievalFields",
    "RollbackMetadata",
    "SQLiteEmbeddingCache",
    "SQLiteTuning",
    "SearchAPI",
    "SearchAvailability",
    "SearchFilters",
    "SearchHit",
    "SearchHitProvenance",
    "SearchKernel",
    "SearchOrchestrator",
    "SearchRequest",
    "SearchResponse",
    "SearchResultProvenance",
    "SearchSource",
    "SearchStrategyStats",
    "SemanticAvailability",
    "SemanticInput",
    "SemanticRecordIngestor",
    "SemanticTier",
    "SourceBatch",
    "SourceCapabilities",
    "SourceIdentity",
    "StrategyContribution",
    "TaskBatchSubmissionResult",
    "TaskSubmissionResult",
    "Tier",
    "ValidationResult",
    "Vector",
    "VectorStore",
    "atomic_write_json",
    "build_embedding_text",
    "build_file_stamps",
    "build_indexed_files_map",
    "build_local_record_kernel",
    "can_refresh_loaded_indices",
    "can_serve_queries",
    "canonical_storage_key",
    "checkpoint_path",
    "classify_query_type",
    "compute_bootstrap_completed_paths",
    "compute_bootstrap_generation",
    "compute_doc_id",
    "compute_doc_id_multi_root",
    "cosine_similarity",
    "cosine_similarity_lists",
    "derive_bootstrap_readiness_snapshot",
    "derive_loaded_index_state_snapshot",
    "discover_files",
    "discover_files_multi_root",
    "embedding_identity",
    "extract_doc_id_from_chunk_id",
    "extract_retrieval_fields",
    "find_excluded_indexed_files",
    "get_bootstrap_availability",
    "get_chunker",
    "get_parser_suffixes",
    "get_semantic_completion_status",
    "has_incomplete_bootstrap_checkpoint",
    "infer_edge_type",
    "is_excluded_dir",
    "is_fully_ready",
    "load_bootstrap_checkpoint",
    "load_manifest",
    "mark_bootstrap_file_completed",
    "mark_bootstrap_files_completed",
    "mark_semantic_work_completed",
    "matches_any_excluded",
    "normalize_path",
    "prepare_bootstrap_checkpoint",
    "publish_bootstrap_availability",
    "reconcile_indices",
    "resolve_doc_path",
    "resolve_doc_path_multi_root",
    "route_query",
    "save_bootstrap_checkpoint",
    "save_manifest",
    "semantic_input_for_chunk",
    "semantic_input_for_record",
    "semantic_tier_from_progress",
    "should_include_file",
    "should_rebuild",
    "should_use_test_fake_embeddings",
    "truncate_content",
    "truncate_delta",
    "walk_dirs_with_files",
    "walk_included_dirs",
]
